const en = {
    appName: "Event App",
    welcome: "Events for Everyone",
    search: "Search",
    comment_placeholder: "Write a comment...",
    add_comment: "Add a comment",
    like: "Like",
    reply: "Reply",
    location: "Location",
    when: "When",
    category: "Category",
    see_more_details: "See more details...",
    see_more: "See more",
    see_less: "See less",
    follow: "Follow",
    unfollow: "Unfollow",
    edit_profile: "Edit Profile",
    configure_profile: "Configure Profile",
    events: "Events",
    followers: "Followers",
    following: "Following",
    started_following_you: "Started Following you",
    liked_your_event: "Liked your event",
    commented_on_your_event: "Commented on your event",
    get_started: "Get Started",
    forgotPassword: "Forgot Password?",
    email: "Email",
    email_placeholder: "email@address.com",
    password: "Password",
    password_placeholder: "Password",
    login: "Login",
    sign_up: "Sign Up",
    username: "Username",
    username_placeholder: "Username",
    fullname: "Full Name",
    fullname_placeholder: "Full Name",
    birthdate: "Birthdate",
    birthdate_placeholder: "Birthdate",
    confirm_password: "Confirm Password",
    confirm_password_placeholder: "Confirm Password",
    check_inbox_for_verification: "Please check your inbox for email verification!",
    choose_categories: "Choose at least 3 categories of your preference:",
    next: "Next",
    success: "Success!",
    success_description: "Your registration has been completed successfully",
    send_link: "Send link", 
    forgot_password_text: "Enter your email address to request a password reset."
}

const es = {
    appName: "Aplicacion de Eventos",
    welcome: "Eventos para todos",
    search: "Buscar",
    comment_placeholder: "Escribe un comentario...",
    add_comment: "Agregar un comentario",
    like: "Me gusta",
    reply: "Responder",
    location: "Ubicación",
    when: "Cuándo",
    category: "Categoría",
    see_more_details: "Ver más detalles...",
    see_more: "Ver más",
    see_less: "Ver menos",
    follow: "Seguir",
    unfollow: "Dejar de seguir",
    edit_profile: "Editar perfil",
    configure_profile: "Configurar perfil",
    events: "Eventos",
    followers: "Seguidores",
    following: "Seguidos",
    started_following_you: "Comenzó a seguirte",
    liked_your_event: "Le gustó tu evento",
    commented_on_your_event: "Comentó en tu evento",
    get_started: "Comenzar",
    forgotPassword: "¿Olvidaste tu contraseña?",
    email: "Correo electrónico",
    email_placeholder: "correo@direccion.com",
    password: "Contraseña",
    password_placeholder: "Contraseña",
    login: "Iniciar sesión",
    sign_up: "Registrarse",
    username: "Nombre de usuario",
    username_placeholder: "Nombre de usuario",
    fullname: "Nombre completo",
    fullname_placeholder: "Nombre completo",
    birthdate: "Fecha de nacimiento",
    birthdate_placeholder: "Fecha de nacimiento",
    confirm_password: "Confirmar contraseña",
    confirm_password_placeholder: "Confirmar contraseña",
    check_inbox_for_verification: "¡Por favor, revisa tu bandeja de entrada para la verificación por correo electrónico!",
    choose_categories: "Selecciona al menos 3 categorías de tu preferencia:",
    next: "Siguiente",
    success: "¡Felicidades!",
    success_description: "Tu registro se ha completado exitosamente",
    send_link: "Enviar enlace", 
    forgot_password_text: "Introduce tu dirección de Correo Electrónico para solicitar el reetablecimiento de tu contraseña."

};

export { en, es };