const en = {
    appName: "Event App",
    welcome: "Welcome to the Event App",
    search: "Search",
    comment_placeholder: "Write a comment...",
    add_comment: "Add a comment",
    like: "Like",
    reply: "Reply",
    location: "Location",
    when: "When",
    category: "Category",
    see_more_details: "See more details...",
    see_more: "See more",
    see_less: "See less",
    follow: "Follow",
    unfollow: "Unfollow",
    edit_profile: "Edit Profile",
    configure_profile: "Configure Profile",
    events: "Events",
    followers: "Followers",
    following: "Following",
    started_following_you: "Started Following you",
    liked_your_event: "Liked your event",
    commented_on_your_event: "Commented on your event",
    // Add more translations as needed
}

const es = {
    appName: "Aplicacion de Eventos",
    welcome: "Bienvenido a la aplicación de eventos",
    search: "Buscar",
    comment_placeholder: "Escribe un comentario...",
    add_comment: "Agregar un comentario",
    like: "Me gusta",
    reply: "Responder",
    location: "Ubicación",
    when: "Cuándo",
    category: "Categoría",
    see_more_details: "Ver más detalles...",
    see_more: "Ver más",
    see_less: "Ver menos",
    follow: "Seguir",
    unfollow: "Dejar de seguir",
    edit_profile: "Editar perfil",
    configure_profile: "Configurar perfil",
    events: "Eventos",
    followers: "Seguidores",
    following: "Seguidos",
    started_following_you: "Comenzó a seguirte",
    liked_your_event: "Le gustó tu evento",
    commented_on_your_event: "Comentó en tu evento",
    // Add more translations as needed
};

export { en, es };
