### TEST API
GET http://localhost:5000/api/users

### ADD user
POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "userId": "asd5a4s543x4c5453a2sd",
  "username": "testuser",
  "fullName": "Test User",
  "email": "testuser@example.com",
  "birthDate": "1990-01-01",
  "language": "ENGLISH"
}

### GET categories
GET http://localhost:5000/api/categories

### GET home events
GET http://localhost:5000/api/home/59f8b967-c1f0-42d3-b9b9-e32c11db446c/events


### LIKE a post
POST http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/like
Content-Type: application/json

{
  "userId": "cm5tzwdmo000dty5cfe8lr1fr"
}

### ADD comment
POST http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/comment
Content-Type: application/json

{
  "userId": "cm5tzwdmo000dty5cfe8lr1fr",
  "text": "This is a test comment."
}

###
GET http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/comments


### GET event details 
GET http://localhost:5000/api/events/cm5zvv4fm0002golor990x1i7/59f8b967-c1f0-42d3-b9b9-e32c11db446c

### ADD event 
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "userId": "cm5x32zqk0000ty28fon5j3yg",
  "eventImage": "https://example.com/image1.jpg",
  "categoryId": 42,
  "latitude": "40.7128",
  "longitude": "-74.0060",
  "title": "Carnaval",
  "description": "A grand celebration to welcome the new year.",
  "date": "2025-01-01T00:00:00.000Z",
  "startsAt": "2025-01-01T19:00:00.000Z",
  "endsAt": "2025-01-01T23:00:00.000Z", 
  "eventMusic": "https://example.com/image1.jpg"
} 
###
POST http://localhost:5000/api/events
Content-Type: application/json
{
  "categoryId": 42, 
  "date": "2025-01-21T16:00:00.000Z" , 
  "description": "aaa", 
  "endsAt": "2025-01-14T05:12:00.000Z" ,
  "eventImage": "https://crnarpvpafbywvdzfukp.supabase.co/storage/v1/object/public/EventImages/1736910739802", 
  "eventMusic": "https://crnarpvpafbywvdzfukp.supabase.co/storage/v1/object/public/EventMusic/1736910743013", 
  "latitude": 37.4220936, 
  "longitude": -122.083922, 
  "startsAt": "2025-01-14T04:12:00.000Z" , 
  "title": "aaa", 
  "userId": "9ae5ed3c-76c3-4b34-8e6e-6619d538e8d7"
}

### Get User events
GET http://localhost:5000/api/users/cm5ylssnm0000ty7wb1c36urk/events

### Get User notifications
GET http://localhost:5000/api/users/9ae5ed3c-76c3-4b34-8e6e-6619d538e8d7/notifications

### POST notification
POST http://localhost:5000/api/notifications
Content-Type: application/json

{
  "fromUserId": "9ae5ed3c-76c3-4b34-8e6e-6619d538e8d7", 
  "toUserId": "59f8b967-c1f0-42d3-b9b9-e32c11db446c", 
  "type":  "FOLLOW", 
  "message": "TESTING NOTIFICATION"
}
### Get User followers
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/followers

### Get User followings
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/following

### Get User profile
GET http://localhost:5000/api/users/cm5ylssnm0000ty7wb1c36urk

### Update User profile
PUT http://localhost:5000/api/users/59f8b967-c1f0-42d3-b9b9-e32c11db446c
Content-Type: application/json

{
  "fullName": "Test User",
  "profileImage": "https://example.com/image1.jpg"
}

### Update User profile
PUT http://localhost:5000/api/users/59f8b967-c1f0-42d3-b9b9-e32c11db446c
Content-Type: application/json

{
  "fullName": "Test User",
  "profileImage": "https://avatars.githubusercontent.com/u/39514914"
}

### Update User profile
PUT http://localhost:5000/api/users/59f8b967-c1f0-42d3-b9b9-e32c11db446c
Content-Type: application/json

{
  "fullName": "Test User xd"
}

### Create location
POST http://localhost:5000/api/locations
Content-Type: application/json

{
  "latitude": 10.2, 
  "longitude": 66.2
}


### Get User followed
GET http://localhost:5000/api/users/59f8b967-c1f0-42d3-b9b9-e32c11db446c/followed

### Get User followers
GET http://localhost:5000/api/users/cm5ylssnm0000ty7wb1c36urk/followers


### Follow User
POST http://localhost:5000/api/users/cm5ylsvds0008ty7wx6ypebvi/follow/59f8b967-c1f0-42d3-b9b9-e32c11db446c

### Unfollow User
DELETE http://localhost:5000/api/users/cm5ylsvds0008ty7wx6ypebvi/unfollow/59f8b967-c1f0-42d3-b9b9-e32c11db446c  

####
DELETE http://localhost:5000/api/locations/cm65ap24y0000tykk9zseji6o

### Search Users
POST http://localhost:5000/api/search/users
Content-Type: application/json

{
  "search": "ruggieroDaniela"
}

### Search Events
POST http://localhost:5000/api/search/events
Content-Type: application/json

{
  "search": "Prueba",
  "userId": "59f8b967-c1f0-42d3-b9b9-e32c11db446c"
}

### Send Notification
POST http://localhost:5000/api/push-notifications/ExponentPushToken[xV4qAGHCCQjDDJN9R1s-g8]
Content-Type: application/json

{
  "title": "Eventify", 
  "body": "Le ha dado like a tu evento"
}

### Like Event
POST http://localhost:5000/api/events/cm63thitt0002ty7okfbjungo/like
Content-Type: application/json

{
  "userId": "59f8b967-c1f0-42d3-b9b9-e32c11db446c"
}

### Get notification token
GET http://localhost:500/api/help

###
GET http://localhost:5000/api/users/9ae5ed3c-76c3-4b34-8e6e-6619d538e8d7/push-notification

###
GET http://localhost:5000/api/user-event/cm65ap3bu0002tykktfdx8htm