### TEST API
GET http://localhost:5000/api/users

### ADD user
POST http://localhost:5000/api/signup
Content-Type: application/json

{
  "userId": "asd5a4s543x4c5453a2sd",
  "username": "testuser",
  "fullName": "Test User",
  "email": "testuser@example.com",
  "birthDate": "1990-01-01",
  "language": "ENGLISH"
}

### GET categories
GET http://localhost:5000/api/categories

### GET home events
GET http://localhost:5000/api/home/events


### LIKE a post
POST http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/like
Content-Type: application/json

{
  "userId": "cm5tzwdmo000dty5cfe8lr1fr"
}

### ADD comment
POST http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/comment
Content-Type: application/json

{
  "userId": "cm5tzwdmo000dty5cfe8lr1fr",
  "text": "This is a test comment."
}

###
GET http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j/comments


### GET event details 
GET http://localhost:5000/api/events/cm5tzwj6l001sty5czanqsk4j

### ADD event 
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "userId": "cm5vrg4ew0000tyq4z7i9rz4m",
  "eventImage": "https://example.com/image1.jpg",
  "categoryId": 32,
  "latitude": "40.7128",
  "longitude": "-74.0060",
  "title": "Carnaval",
  "description": "A grand celebration to welcome the new year.",
  "date": "2025-01-01T00:00:00.000Z",
  "startsAt": "2025-01-01T19:00:00.000Z",
  "endsAt": "2025-01-01T23:00:00.000Z"
} 

### Get User events
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/events

### Get User notifications
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/notifications

### Get User followers
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/followers

### Get User followings
GET http://localhost:5000/api/users/cm5tzwbk50000ty5c57ia1ca6/following

