### TEST API
GET http://localhost:5000/api/users

### GET event details 
GET http://localhost:5000/api/events/cm5tuv5ct001qtyn456718gm

### ADD event 
POST http://localhost:5000/api/events
Content-Type: application/json

{
  "userId": "cm5tuuz6l0000tyn4vcrz9ks7",
  "eventImage": ["https://example.com/image1.jpg"],
  "categoryId": "cm5tuv1kv000ktyn4gz9x1y82",
  "latitude": "40.7128",
  "longitude": "-74.0060",
  "title": "New Year's Party",
  "description": "A grand celebration to welcome the new year.",
  "date": "2025-01-01T00:00:00.000Z",
  "startsAt": "2025-01-01T19:00:00.000Z",
  "endsAt": "2025-01-01T23:00:00.000Z"
} 